# Generated by Django 5.2.6 on 2025-10-02 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('subscriptions', '0002_service_remove_subscription_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='subscription_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.userservicesubscription'),
        ),
    ]
