# Generated by Django 5.2.6 on 2025-09-22 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tryon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tryonrequest',
            name='garment_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tryonrequest',
            name='human_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tryonrequest',
            name='garment_image',
            field=models.ImageField(blank=True, null=True, upload_to='tryon/garment_images/'),
        ),
        migrations.AlterField(
            model_name='tryonrequest',
            name='human_image',
            field=models.ImageField(blank=True, null=True, upload_to='tryon/human_images/'),
        ),
    ]
