# Generated by Django 5.2.6 on 2025-10-02 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tryon', '0003_tryonrequest_demo_invitation_alter_tryonrequest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tryonrequest',
            name='garment_image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='tryonrequest',
            name='human_image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='tryonrequest',
            name='result_image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
