# Generated by Django 5.2.6 on 2025-09-14 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='seller',
        ),
    ]
