# Generated by Django 5.2.6 on 2025-10-02 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_subscription_id'),
        ('subscriptions', '0002_service_remove_subscription_plan_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.DeleteModel(
            name='SubscriptionHistory',
        ),
        migrations.AlterUniqueTogether(
            name='userservicesubscription',
            unique_together={('user', 'service')},
        ),
    ]
